spring.application.name=AUTH-SERVICE

server.port=8081

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

# ===============================
# MYSQL DATABASE
# ===============================

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/smartops_auth}

spring.datasource.username=${MYSQL_USERNAME}

spring.datasource.password=${MYSQL_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# EUREKA
# ===============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET}

# ===============================
# KAFKA
# ===============================

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

logging.level.org.springframework.security=INFO

server.error.include-message=never
server.error.include-binding-errors=never

app.cookie.secure=${COOKIE_SECURE:true}
app.cookie.same-site=${COOKIE_SAME_SITE:Lax}

spring.kafka.consumer.properties.spring.json.trusted.packages=com.smartops.common.event
