# =========================
# SERVER
# =========================
server.port=8080
spring.application.name=api-gateway

# =========================
# ACTUATOR (DEBUG ROUTES)
# =========================
management.endpoint.gateway.access=read_only
management.endpoints.web.exposure.include=gateway

# =========================
# EUREKA
# =========================
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka
eureka.instance.prefer-ip-address=true

# =========================
# GATEWAY ROUTES (CORRECT)
# =========================

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=monitoring-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://MONITORING-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/monitor/**, /api/logs/**

spring.cloud.gateway.server.webflux.routes[2].id=alert-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ALERT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/alerts/**

# =========================
# WEBSOCKET ROUTES (CORRECT)
# =========================
spring.cloud.gateway.server.webflux.routes[3].id=alert-ws
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ALERT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/ws/**

# =========================
# GLOBAL CORS (CORRECT)
# =========================
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true

# =========================
# LOGGING
# =========================
logging.level.org.springframework.cloud.gateway=DEBUG

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.smartops.common.event