package com.smartops.alert.kafka;

import com.smartops.alert.dto.CreateAlertRequest;
import com.smartops.alert.model.AlertSeverity;
import com.smartops.alert.model.AlertStatus;
import com.smartops.alert.service.AlertService;
import com.smartops.common.event.LogEvent;
import lombok.RequiredArgsConstructor;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;
@Component
@RequiredArgsConstructor
public class AlertKafkaConsumer {

    private final AlertService alertService;

    @KafkaListener(
            topics = "smartops-logs",
            groupId = "alert-group"
    )
    public void consume(LogEvent event) {

        System.out.println("🔥 LOG RECEIVED: " + event);

        // Ignore logs generated by Alert Service itself
        if ("ALERT".equalsIgnoreCase(event.getServiceName())) {
            return;
        }

        // Only process service down events
        if (event.getMessage() == null || !event.getMessage().contains("Service DOWN")) {
            return;
        }

        if (event.getUserId() == null || event.getUserId().isBlank()) {
            // A service-down event without an owner cannot safely create an alert.
            return;
        }

        CreateAlertRequest request = new CreateAlertRequest();

        request.setServiceName(extractServiceName(event.getMessage()));
        request.setUserId(event.getUserId());
        request.setSeverity(AlertSeverity.CRITICAL);
        request.setTitle("Service Alert");
        request.setMessage(event.getMessage());
        request.setStatus(AlertStatus.ACTIVE);

        alertService.createAlert(request);
    }

    private String extractServiceName(String message) {
        return message.replace("Service DOWN: ", "");
    }
}
